### ISSUE TITLE
docker hub免費的private repo

### ISSUE THREAD

**Issue by leo424y** [twgo/gi2-gian5_boo5-hing5#3]
可以有1個，不知夠不夠用
有預算的話升五個只要$7/month或更多較乾脆
https://hub.docker.com/billing-plans/ 

DIY
https://github.com/docker/docker.github.io/blob/master/registry/deploying.md
https://github.com/docker/distribution

https://medium.com/@adascalitei.victor/deploying-a-self-hosted-free-public-certified-docker-registry-the-docker-way-3bcc397270ca
https://philipzheng.gitbooks.io/docker_practice/content/repository/local_repo.html

**Comment by sih4sing5hong5** [comment]
`聲學模型`算一个Repositories ？

`Builds`是指`docker build`？

**Comment by leo424y** [comment]
是的，聲學模型算一個 Repositories  (Githube repo= Docker repo)

Builds是指docker build，paid version 可以同步進行，

若只有聲學需要private(需要跨主機)的話，可以開一個公用帳號以private先推看看。

已開： https://hub.docker.com/r/gotw
且new private gotw/siann1-hak8_boo5-hing5

註：試過用組織開，無private額度

**Comment by leo424y** [comment]
https://forums.docker.com/t/does-docker-hub-have-a-size-limitation-on-repos-or-images/10154
>A repository can have any number of image tags. There is not a stated limit for size. In practice, if an image layer gets much larger than 10 or 20 gigabytes, you may experience problems with push and pull. Your mileage may vary.

>There is no limit for builds or tags.

builds or tags無限，推大檔可能會有問題，不過，試了再說！

**Comment by leo424y** [comment]
已能  self host image docker  讚讚
