### ISSUE TITLE
branch name 需要是英文

### ISSUE THREAD

**Issue by leo424y** [twgo/gi2-gian5_boo5-hing5#7]
@sih4sing5hong5 

因為ruby有點弱弱，

我用的api gem不支援中文branch name
 
實驗用的branch name可以只用英文嗎？ 

commit, tag 內容用中文沒問題的！

目前有中文的就

https://github.com/twgo/gi2-gian5_boo5-hing5/tree/%E8%AA%9E%E8%A8%80%E6%A8%A1%E5%9E%8B

https://github.com/twgo/gi2-gian5_boo5-hing5/tree/free-syllable-tw01test-%E4%BB%9D%E8%AA%9E%E8%80%85

麻煩幫忙一下，大感謝！

**Comment by sih4sing5hong5** [comment]
修彼个gem呀 XD

最近就先改名，一兩個月了後，你較有時間才去修這个gem？

**Comment by leo424y** [comment]
@sih4sing5hong5 

酷耶！opensource 大好！等初步實驗動能就來修 gem ，一定要讓它支援漢字啊

另外發現聲學用+也會噴，勞煩大隊長幫幫忙修聲學的branch ，plz.. ！

目前 gi2-gian5_boo5-hing5 接 siann1-hak8_boo5-hing5 OK 了！

除了 branch 有中文和+撈不到

可以選要接的build

也可以直接改 dockerfile

改完送出就會commit
歡迎亂玩...  http://10.32.0.124:3000/

**Comment by leo424y** [comment]
> 修彼个gem呀 XD  



已解 
結果是url encode 的小事
不過還是有發現可以改文件的PR可以發
感謝當頭棒喝！

**Comment by leo424y** [comment]
> 最近就先改名，一兩個月了後，你較有時間才去修這个gem？

可以不用改branch 名了encode後就完全支援

https://github.com/twgo/twgo-exp/pull/6
